version: "3.9"

networks:
  backend:

services:
  web:
    build: ./django_app
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:5000
    networks:
      - backend
    volumes:
      - ./django_app/:/usr/src/django_app/
      - ./django_app/static:/usr/src/django_app/static/
    env_file:
      - ./django_app/.env
    depends_on:
      - db_postgres
  db_postgres:
    image: postgres:latest
    networks:
      - backend
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./django_app/.env
  nginx:
    build: ./nginx
    networks:
      - backend
    volumes:
      - ./django_app/static:/usr/src/django_app/static/
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  postgres_volume:
